### ISSUE TITLE
nullmodem driver for newer kernels (3.8, 4 series)

### ISSUE THREAD

**Issue by twitzelbos** [pitti98/nullmodem#2]
I found this very interesting driver that can be useful for some development that I'm doing. I modified my fork to compile on a 4.15 kernel. Still need to do some exhaustive testing.

**Comment by Tarnyko** [comment]
Hi @twitzelbos,
Please check [this](https://github.com/pitti98/nullmodem/pull/3).

**Comment by pitti98** [comment]
Merged pull request.
